### ISSUE TITLE
Release new pokemons

### ISSUE THREAD

**Issue by kukko** [anvit/pokesay#2]
Hello!

Can you please release a new version of the package to npm which contains the newly added Pokemons? :)

**Comment by anvit** [comment]
Just published! [Pokesay v1.1.4](https://www.npmjs.com/package/pokesay/v/1.1.4)
![pikachu party](https://github.com/anvit/pokesay/assets/2498062/270cc0e3-c83a-4f3c-bf9e-f518c5f5ee9e)
